exclude: "^.github/"
repos:
-   repo: https://github.com/google/yapf.git
    rev: v0.40.2
    hooks:
    -   id: yapf
        additional_dependencies: [toml]
-   repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v4.1.0
    hooks:
    -   id: trailing-whitespace
        exclude: \.fits
    -   id: end-of-file-fixer
        exclude: \.fits
    -   id: check-yaml
    -   id: debug-statements
    -   id: requirements-txt-fixer
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-merge-conflict
