#!/bin/bash

tnew="tmux new-session -d -s"
tsend="tmux send-keys -t"

tname="glint_ctrl"

# Create tmuxes and issue kills
$tnew $tname
sleep 3.0 # Don't send the ctrl+C too fast, it'll nuke the bashrc sourcing !
$tsend $tname C-c
sleep 0.1
$tsend $tname "close()" Enter
sleep 3
$tsend $tname C-c
sleep 0.3
$tsend $tname C-z
sleep 0.3
$tsend $tname "kill %" Enter

echo ""
#read -p "Everything killed, proceed to startup ? Press enter to continue, Ctrl+C to abort."

echo "Resetting KAYA boxes config - should not require sudo anymore... ?"
DEV="/dev/serial/by-id/usb-Silicon_Labs_CP2101_USB_to_UART_Bridge_Controller_0001-if00-port0"

sudo stty -F ${DEV} 115200 raw -echo -echoe -echok -echoctl -echoke
sleep 1
echo -e -n 'FORMAT 3 1\r' | sudo tee ${DEV}
sleep 1
echo -e -n 'UARTBAUD 0 4\r' | sudo tee ${DEV}

$tsend $tname "python -im camstack.cam_mains.glintcam" Enter

echo "startGLINT completed."
