#!/bin/bash

# SYNTAX
# ./firststart <sizex> <sizey>

# RATIONALE
# Kill and restart the first cam stuff
# This is temporary until I get the edtcam python stack done

# Sequence
# (Re-)create tmuxes:
# vcam(0|1)_edt: framegrabbing
# vcam(0|1)_serial: serial to Andors (probs not implemented, will delete)
# REMOTE @scexao5 streamTCPreceive_3010(4|5): shmimTCPreceive
# vcam(0|1)_tcp: TCP receive

if [ "$#" -ne 2 ]; then
    SIZE_W=512
    SIZE_H=204
else
    SIZE_W=$1
    SIZE_H=$2
fi;

# Input
NUM=$1
SIZE_X=$2
echo ""
read -p "Starting FIRST FG with size ${SIZE_W} x ${SIZE_H} ?"

# Inspect csets
cset set
echo ""
read -p "cpusets looking OK ? Press enter to continue, Ctrl+C to abort."

# aliases
SC5="133.40.161.194"
PORT="30106"
SC5tmux="streamTCPreceive_${PORT}"

tnew="tmux new-session -d -s"
tsend="tmux send-keys -t"

# Create tmuxes and issue kills
$tnew first_edt
$tnew first_tcp
echo "ssh $SC5 \"$tnew $SC5tmux -d\""
ssh $SC5 "$tnew $SC5tmux -d"

$tsend first_tcp C-c
sleep 0.2
$tsend first_edt C-c
sleep 0.2
echo "ssh $SC5 \"$tsend $SC5tmux C-c\""
ssh $SC5 $tsend $SC5tmux C-c
sleep 0.2

echo ""
read -p "Everything killed, proceed to startup ? Press enter to continue, Ctrl+C to abort."

# STARTUP
# EDT FG
# Gen file at right size
CFG_FILE="/home/scexao/src/camstack/config/first_sedfile.cfg"
TMP_FILE="/home/scexao/src/camstack/config/first_tmp.cfg"
sed s/SED_WIDTH_HERE/${SIZE_W}/ $CFG_FILE | sed s/SED_HEIGHT_HERE/${SIZE_H}/ > $TMP_FILE

$tsend first_edt "/opt/EDTpdv/initcam -u 0 -c 1 -f ${TMP_FILE}" Enter
$tsend first_edt "/home/scexao/src/camstack/src/edttake -s firstcam -u 0 -c 1 -l 0 -N 4" Enter
sleep 1
# Then TCP, receiver, then transmitter
ssh $SC5 "$tsend $SC5tmux \"milk\" Enter"
ssh $SC5 "$tsend $SC5tmux \"creaushortimshm firstcam ${SIZE_W} ${SIZE_H}\" Enter"
ssh $SC5 "$tsend $SC5tmux \"exit\" Enter"
ssh $SC5 "$tsend $SC5tmux \"shmimTCPreceive -c aol0COM ${PORT}\" Enter"
sleep .5
$tsend first_tcp "OMP_NUM_THREADS=1 /home/scexao/bin/shmimTCPtransmit firstcam 10.20.70.1 ${PORT}" Enter
sleep 1

# Then send the RT prio and cset setting
PID=$(pgrep -f "edttake -s firstcam")
sudo cset proc --threads -m $PID first_edt > /dev/null
sudo chrt -f -p 49 $PID > /dev/null

PID=$(pgrep -f shmimTCPtransmit-firstcam)
sudo cset proc --threads -m $PID first_tcp > /dev/null
sudo chrt -f -p 47 $PID > /dev/null

echo ""
echo ""
cset proc first_edt
cset proc first_tcp

echo "firststart ${SIZE_W} ${SIZE_H} completed."