#!/bin/bash

echo "\n---- Killing all displays. ----"
cmd="killall chuckcam"
echo $cmd
$cmd

echo "\n---- Nuking camera servers ----"
cmd="ssh scexao-op@localhost \"tmux kill-server\""
echo $cmd
bash -c "$cmd"
sleep 5

echo "\n---- Reloading edt module (sudo password) ----"
cmd="sudo /opt/EDTpdv/edtinit restart"
$cmd
sleep 2

echo "\n---- start chuck ----"
cmd="startCRED2"
$cmd
sleep 1
# echo "\n---- start Buffy ----"
# cmd="startKCAM"
# $cmd
# sleep 1

cmd="ssh scexao-op@localhost \"tmux new -d -s kcam_zmq\""
echo $cmd
bash -c "$cmd"
sleep 1

cmd="ssh scexao-op@localhost tmux send-keys -t kcam_zmq \"zmq_recv.py\ 10.20.30.5:33000\ kcam\" Enter"
echo $cmd
bash -c "$cmd"

sleep 10
chuckcam &
# buffycam &

