#!/bin/bash

tnew="tmux new-session -d -s"
tsend="tmux send-keys -t"

tname="ircam0ctrl"

# Create tmuxes and issue kills
$tnew $tname
sleep 0.1
$tsend $tname C-c
sleep 0.1
$tsend $tname "close()" Enter
sleep 3
$tsend $tname C-c
sleep 0.3
$tsend $tname C-z
sleep 0.3
$tsend $tname "kill %" Enter

echo ""
#read -p "Everything killed, proceed to startup ? Press enter to continue, Ctrl+C to abort."

$tsend $tname "python -im camstack.cam_mains.chuckcam" Enter

echo "startChuck completed."

