#!/bin/bash

# RATIONALE
# Kill and restart the ocam stuff
# This is temporary until I get the edtcam python stack done

# Sequence - performed by the ocam_ctrl python
# (Re-)create tmuxes:
# ocam_edt: framegrabbing
# ocam_decode: OCAM2K demangling
# ocam_serial: serial to OCAM2K
# REMOTE @scexao5 streamTCPreceive_30107: shmimTCPreceive
# ocam_tcp: TCP receive

tnew="tmux new-session -d -s"
tsend="tmux send-keys -t"

tname="ocam_ctrl"

# Create tmuxes and issue kills
$tnew $tname
sleep 3.0 # Don't send the ctrl+C too fast, it'll nuke the bashrc sourcing !
$tsend $tname C-c
sleep 0.1
$tsend $tname "close()" Enter
sleep 3
$tsend $tname C-c
sleep 0.3
$tsend $tname C-z
sleep 0.3
$tsend $tname "kill %" Enter

echo ""
#read -p "Everything killed, proceed to startup ? Press enter to continue, Ctrl+C to abort."

$tsend $tname "python -im camstack.cam_mains.renocam" Enter

echo "startOCAM completed."
