#!/bin/bash

# SYNTAX
# ./vcamstart (0|1) <size>

# RATIONALE
# Kill and restart the vampires cam stuff
# This is temporary until I get the edtcam python stack done

# Sequence
# (Re-)create tmuxes:
# first_edt: framegrabbing
# REMOTE @scexao5 streamTCPreceive_30106: shmimTCPreceive
# first_tcp: TCP receive

# Input
NUM=$1
SIZE=$2
echo ""
read -p "Starting camera ${NUM} with size ${SIZE} ?"

# Inspect csets
cset set
echo ""
read -p "cpusets looking OK ? Press enter to continue, Ctrl+C to abort."

# aliases
TARG_IP=$IP_SC6_LAN
name=VCAM${NUM}_PORT
PORT=echo(${!name})
targ_tmux="streamTCPreceive_${PORT}"

tnew="tmux new-session -d -s"
tsend="tmux send-keys -t"

# Create tmuxes and issue kills
$tnew vcam${NUM}_edt
$tnew vcam${NUM}_tcp
$tnew vcam${NUM}_serial # Tentative
echo "ssh $TARG_IP \"$tnew $TARG_IPtmux -d\""
ssh $TARG_IP "$tnew $targ_tmux -d"

$tsend vcam${NUM}_tcp C-c
sleep 0.2
$tsend vcam${NUM}_edt C-c
sleep 0.2
$tsend vcam${NUM}_serial C-c
sleep 0.2
echo "ssh $TARG_IP \"$tsend $targ_tmux C-c\""
ssh $TARG_IP $tsend $targ_tmux C-c
sleep 0.2

echo ""
read -p "Everything killed, proceed to startup ? Press enter to continue, Ctrl+C to abort."

# STARTUP
# EDT FG
# Gen file at right size
CFG_FILE="/home/scexao/src/camstack/config/vampires_sedfile.cfg"
TMP_FILE="/home/scexao/src/camstack/config/vampires_tmp.cfg"
sed s/SED_HW_HERE/${SIZE}/ $CFG_FILE > $TMP_FILE

# Clear shmim and sems
rm /milk/shm/vcamim${NUM}.im.shm
rm /dev/shm/sem..milk.shm.vcamim${NUM}_*
# Start the take
$tsend vcam${NUM}_edt "/opt/EDTpdv/initcam -u 2 -c ${NUM} -f ${TMP_FILE}" Enter
$tsend vcam${NUM}_edt "/home/scexao/src/camstack/src/edttake -s vcamim${NUM} -u 2 -c ${NUM} -l 0 -N 4 -U" Enter
sleep 1
# Then TCP, receiver, then transmitter
ssh $TARG_IP "$tsend $targ_tmux \"milk\" Enter"
ssh $TARG_IP "$tsend $targ_tmux \"creaushortimshm vcamim${NUM} ${SIZE} ${SIZE}\" Enter"
ssh $TARG_IP "$tsend $targ_tmux \"exit\" Enter"
ssh $TARG_IP "$tsend $targ_tmux \"shmimTCPreceive -c aol0COM ${PORT}\" Enter"
sleep .5
$tsend vcam${NUM}_tcp "OMP_NUM_THREADS=1 /home/scexao/bin/shmimTCPtransmit vcamim${NUM} ${IP_SC6_P2P70} ${PORT}" Enter
sleep 1

# Then send the RT prio and cset setting
PID=$(pgrep -f "edttake -s vcamim${NUM}")
sudo cset proc --threads -m $PID vcam_edt > /dev/null
sudo chrt -f -p 49 $PID > /dev/null

PID=$(pgrep -f shmimTCPtransmit-vcamim${NUM})
sudo cset proc --threads -m $PID vcam_tcp > /dev/null
sudo chrt -f -p 47 $PID > /dev/null

echo ""
echo ""
cset proc vcam_edt
cset proc vcam_tcp

echo "vcamstart ${NUM} ${SIZE} completed."
