#!/bin/env python

'''
    vcamstart python argument checker
    Will fail if the syntax is wrong, will proceed to the bash script if OK.

    Usage:
        vcamstart 0 <size>
        vcamstart 1 <size>
'''

from docopt import docopt
import sys
import subprocess

from camstack.core.utilities import enforce_whichcomp

if __name__ == "__main__":

    enforce_whichcomp('5')

    args = docopt(__doc__) # Argument checking really

    if int(args["<size>"]) not in [32, 64, 128, 256, 512]:
        raise ValueError("<size> not in [32, 64, 128, 256, 512]")

    run_line = ['vcamstart-bash'] + sys.argv[1:]
    print(run_line)
    try:
        subprocess.run(run_line)
    except KeyboardInterrupt:
        print('-Aborted-')

