#!/bin/sh

if [ -z "$MILK_ROOT" ]; then
    MILK_ROOT=${CACAO_ROOT};
fi
ISIO_ROOT=${MILK_ROOT}/src/ImageStreamIO

gcc edttake.c -o edttake -I/opt/EDTpdv -I${ISIO_ROOT} -I${CACAO_ROOT}/src ${ISIO_ROOT}/ImageStreamIO.c /opt/EDTpdv/libpdv.a -Wall -Wno-format-truncation  -Wno-format-overflow -lm -lpthread -ldl
