APAPANE = BUFFY = 'APAPANE'
IIWI = 'IIWI'
PALILA = CHUCK = 'PALILA'
FIRST = 'FIRST'
GLINT = 'GLINT'
KIWIKIU = KIWI = RAJNI = 'KIWIKIU'
PUEO = RENO = OCAM = 'PUEO'
VCAM1 = "VCAM1"
VCAM2 = "VCAM2"
VPUPCAM = VPUP = "VPUPCAM"
ALALA = "ALALA"
